mode: nbvh
log_dir: runsx

mesh:
  # path: "lego_decimated.stl"
  path: "suzanne.fbx"
  split_faces: 0.8
  bvh_depth: 15

train:
  lr: 0.001
  total_size: 100000000
  batch_size: 100000

val:
  total_size: 1000000
  batch_size: 10000

cam:
  img_size: 800
  batch_size: 160000
