mode: nbvh
log_dir: runs7

mesh:
  path: "lego_decimated.stl"
  split_faces: 0.8
  bvh_depth: 25

train:
  lr: 0.001
  total_size: 50000000
  batch_size: 200000

val:
  total_size: 1000000
  batch_size: 10000

cam:
  img_size: 800
  batch_size: 160000
