mode: raytrace
log_dir: runs7

mesh:
  path: "datasets/lego_mesh/lego_decimated.stl"
  split_faces: 0.8
  bvh_gen_depth: 25
  bvh_depth: 15

train:
  lr: 0.001
  total_size: 10000000
  batch_size: 10000

val:
  total_size: 1000000
  batch_size: 10000

cam:
  img_size: 800
  batch_size: 160000
